# Generated by Django 4.2 on 2023-05-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="zipcode",
            field=models.CharField(max_length=10),
        ),
    ]
