# Generated by Django 4.2 on 2023-05-05 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcart",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_cart_list",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ManyToManyField(
                related_name="cart", through="cart.ProductCart", to="products.product"
            ),
        ),
    ]
