# Generated by Django 4.2 on 2023-05-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pedido realizado', 'Realizado'), ('Pedido em andamento', 'Andamento'), ('Pedido entregue', 'Entregue')], default='Pedido em andamento', max_length=20)),
                ('buyed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
