# Generated by Django 4.2 on 2023-05-08 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_order', to='products.product'),
        ),
    ]
