# Generated by Django 4.2 on 2023-05-10 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
        ("orders", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userorder",
            name="products",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_order",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="userorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Realizado", "Realizado"),
                    ("Em andamento", "Andamento"),
                    ("Entregue", "Entregue"),
                ],
                default="Realizado",
                max_length=20,
            ),
        ),
    ]
