# Generated by Django 4.2 on 2023-05-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Botas', 'Botas'), ('Chinelos e Sandálias', 'Chinelos Sandalias'), ('Chuteiras', 'Chuteiras'), ('Sapatênis', 'Sapatenis'), ('Tênis', 'Tenis'), ('Tênis de corrida', 'Tenis Corrida')], default='Botas', max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image_product', models.URLField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
