# Generated by Django 4.2 on 2023-05-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Botas", "Botas"),
                            ("Chinelos e Sandálias", "Chinelos Sandálias"),
                            ("Chuteiras", "Chuteiras"),
                            ("Sapatênis", "Sapatênis"),
                            ("Tênis", "Tênis"),
                            ("Tênis de corrida", "Tênis Corrida"),
                        ],
                        default="Botas",
                        max_length=20,
                    ),
                ),
                ("quantities", models.IntegerField(default=0)),
                ("bio", models.TextField()),
                ("image_product", models.URLField()),
                ("cart", models.ManyToManyField(related_name="cart", to="cart.cart")),
            ],
        ),
    ]
