# Generated by Django 4.2 on 2023-05-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Botas", "Botas"),
                    ("Chinelos e Sandálias", "Chinelos Sandalias"),
                    ("Chuteiras", "Chuteiras"),
                    ("Sapatênis", "Sapatenis"),
                    ("Tênis", "Tenis"),
                    ("Tênis de corrida", "Tenis Corrida"),
                ],
                default="Botas",
                max_length=20,
            ),
        ),
    ]
