# Generated by Django 4.2 on 2023-05-04 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="bio",
            new_name="description",
        ),
    ]
