# Generated by Django 4.2 on 2023-05-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantities',
            new_name='stock',
        ),
    ]
